### PR TITLE
Add device_config to test option for customer models

### PR DESCRIPTION
**Pull request by ashokkumarkannan1**

### CODE REVIEW

**Review by nvukobratTT — APPROVED** [review]

**Comment by nvukobratTT** [comment]
@milank94 would like to hear your opinion on including test_device within the test name. 

For proper CI testing and easier device type specification (e.g. n150, n300, e150, e300, etc) we need to make these kinds of changes. Have in mind that this is mostly for Golden running and testing purposes. 

Let me know if this is problematic for the tt-buda-demos side. If yes, going forward we can discuss the potential discard of Golden tracking/testing on our end, and only focus on silicon runs for this model demos. 

Before making any conclusions, let me know your thoughts.

**Comment by milank94** [comment]
> @milank94 would like to hear your opinion on including test_device within the test name.
> 
> For proper CI testing and easier device type specification (e.g. n150, n300, e150, e300, etc) we need to make these kinds of changes. Have in mind that this is mostly for Golden running and testing purposes.
> 
> Let me know if this is problematic for the tt-buda-demos side. If yes, going forward we can discuss the potential discard of Golden tracking/testing on our end, and only focus on silicon runs for this model demos.
> 
> Before making any conclusions, let me know your thoughts.

Thanks @nvukobratTT. My thoughts on this:

- If the changes are only in the `tests/` directory and do not impact the core demos that are meant to be external/customer facing, then I don't see any issues with adding these configurations, as it helps with testing and CI purposes. 
- My only concern is that if these settings are inducing any "hidden" configuration changes to the model implementation when running on silicon that might not be set if a user tries to run the demo script directly. I can review the `conftest.py` file, either in this PR or when we attempt to merge into `main`, if easier. When we test these scripts, I just want to sure everything is accounted for and it's run the exact same way a user would run it, end-to-end.

**Comment by nvukobratTT** [comment]
Thanks for your thoughts @milank94! Yes,
- These changes are related only to `tests/` directory and are purely impacting our testing infrastructure.
- There shouldn't be any "hidden" changes that will impact model demos. Customers should have unchanged interface and behavior of their models

If it works for you, let's merge these changes into tracking branch, and you can have a more detailed overview before we officially merge those into the main branch.

**Comment by milank94** [comment]
> Thanks for your thoughts @milank94! Yes,
> 
> * These changes are related only to `tests/` directory and are purely impacting our testing infrastructure.
> * There shouldn't be any "hidden" changes that will impact model demos. Customers should have unchanged interface and behavior of their models
> 
> If it works for you, let's merge these changes into tracking branch, and you can have a more detailed overview before we officially merge those into the main branch.

Sounds great. Thanks @nvukobratTT

**Pull request merged**
